# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bb80987ed7190954c43245e0f23c88fc2a92262fe9e97f4d1e38c348eaef8c788e5a4d748e308c5132f20604723f4af69a2060e1be163b6d4cfee335d422ba08

test:
  secret_key_base: 4b5728c95f03afd4e6928048045e8473cd7f9d44aa4148cf4c7ea967f3516693f21a6fa5194d827bec94ced8da628aaba1209cab091eca0a85362ed194cbccae

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
